import { z } from 'zod'
import { WITHDRAWAL_STRATEGIES } from '@/types'

export const ReportLocaleSchema = z.enum(['en', 'de'])
export type ReportLocale = z.infer<typeof ReportLocaleSchema>

export const DEFAULT_REPORT_LOCALE: ReportLocale = 'de'

// Validation schemas with min/max ranges
export const PersonSchema = z.object({
  currentAge: z.number().min(18).max(100),
  retireAge: z.number().min(50).max(80),
  pensionAge: z.number().min(60).max(80),
  horizonAge: z.number().min(70).max(120),
})

export const FinancesSchema = z.object({
  currentAssetsEUR: z.number().min(0).max(100_000_000),
  annualSavingsEUR: z.number().min(0).max(1_000_000),
  expectedMonthlyPensionEUR: z.number().min(0).max(50_000),
})

export const SpendingSchema = z.object({
  monthly: z.object({
    health: z.number().min(0).max(10_000),
    food: z.number().min(0).max(10_000),
    entertainment: z.number().min(0).max(10_000),
    shopping: z.number().min(0).max(10_000),
    utilities: z.number().min(0).max(10_000),
  }),
  annual: z.object({
    vacations: z.number().min(0).max(100_000),
    homeRepairs: z.number().min(0).max(100_000),
    car: z.number().min(0).max(100_000),
  }),
  custom: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
        // Translation key for a flow the app seeded, so the report can print
        // "Lebensmittel" instead of "Groceries". Absent once renamed.
        nameKey: z.string().max(64).optional(),
        amount: z.number().min(0).max(1_000_000),
        interval: z.enum(['monthly', 'annual']),
      })
    )
    .default([]),
  /**
   * Scheduled cash flows — the ones `custom` cannot express: income, an age
   * window, a single payment, a nominally fixed amount. Optional so reports
   * generated by an older client still validate.
   */
  cashFlows: z
    .array(
      z.object({
        id: z.string(),
        kind: z.enum(['income', 'expense']),
        name: z.string(),
        nameKey: z.string().max(64).optional(),
        amount: z.number().min(0).max(100_000_000),
        frequency: z.enum(['monthly', 'annual', 'once']),
        startAge: z.number().min(0).max(120).optional(),
        endAge: z.number().min(0).max(120).optional(),
        inflationLinked: z.boolean().optional(),
        growthRate: z.number().min(-1).max(1).optional(),
      })
    )
    .default([]),
})

export const AssumptionsSchema = z.object({
  roiMean: z.number().min(-0.2).max(0.3),
  roiStdev: z.number().min(0).max(0.5),
  inflationMean: z.number().min(-0.05).max(0.15),
  inflationStdev: z.number().min(0).max(0.1),
  // Sourced from the app's own strategy list so a new strategy cannot ship
  // without the report being able to name it.
  withdrawalStrategy: z.enum(WITHDRAWAL_STRATEGIES).default('vanguardDynamic'),
  /**
   * Market model and allocation glide path. Defaulted so reports generated
   * before these existed still validate as "Monte Carlo, single asset".
   */
  marketModel: z.enum(['monteCarlo', 'historical']).default('monteCarlo'),
  glidePathEnabled: z.boolean().default(false),
  equityAllocationStart: z.number().min(0).max(1).default(0.8),
  equityAllocationEnd: z.number().min(0).max(1).default(0.4),
  bondReturn: z.number().min(-0.2).max(0.3).default(0.03),
  bondVolatility: z.number().min(0).max(0.5).default(0.06),
  dsWithdrawalRate: z.number().min(0).max(1).default(0.05),
  dsCeilingRate: z.number().min(0).max(1).default(0.05),
  dsFloorRate: z.number().min(-1).max(0).default(-0.025),
  /** `percentOfPortfolio` spending floor, today's euros per year. */
  spendingFloorReal: z.number().min(0).default(0),
  // Fix absurd tax rates like 2625% -> cap at 80%
  capGainsTaxRatePct: z
    .number()
    .min(0)
    .transform((val) => {
      // Detect likely typos (e.g., 2625 instead of 26.25)
      if (val > 100) {
        const corrected = val / 100
        if (corrected <= 80) {
          return corrected
        }
        return 80 // Cap at 80% if still too high
      }
      return Math.min(val, 80)
    }),
  /**
   * German tax detail and the bequest goal. Defaulted to the neutral values so
   * a report generated before they existed still validates as the flat model
   * it was actually run with.
   */
  taxAllowanceAnnual: z.number().min(0).max(100_000).default(0),
  householdType: z.enum(['single', 'couple']).default('single'),
  equityFundExemption: z.number().min(0).max(1).default(0),
  pensionTaxablePortion: z.number().min(0).max(1).default(0),
  pensionTaxRate: z.number().min(0).max(1).default(0),
  legacyTargetReal: z.number().min(0).default(0),
  mcRuns: z.number().min(100).max(100_000),
})

/**
 * The simulation context: what the engine actually did, carried verbatim from
 * the app so the report cannot invent a run count, a market model or a success
 * definition of its own.
 *
 * Optional as a whole — a payload from an older client simply lacks it, and
 * `mapReportDataToContent` reconstructs the best available approximation from
 * `assumptions` + `projections` instead of failing validation.
 */
export const SimulationSchema = z.object({
  marketModel: z.enum(['monteCarlo', 'historical']).default('monteCarlo'),
  /** Paths really run: `simulationRuns` under Monte Carlo, 125 under historical. */
  effectiveRuns: z.number().min(1).max(1_000_000),
  successDefinition: z.enum(['legacyConditioned', 'depletion']).default('depletion'),
  successRatePct: z.number().min(0).max(100),
  depletionSuccessRatePct: z.number().min(0).max(100),
  depletionRiskPct: z.number().min(0).max(100).default(0),
  successCount: z.number().min(0),
  /** Simulated years, taken from the engine's age grid (inclusive of both ends). */
  horizonYears: z.number().min(1).max(120),
  legacyTargetReal: z.number().min(0).default(0),
  seedLabel: z.string().default(''),
  paramsFingerprint: z.string().default(''),
  computedAt: z.string().optional(),
  historicalPathCount: z.number().min(1).default(125),
  historicalFirstYear: z.number().default(1900),
  historicalLastYear: z.number().default(2024),
})

export const MilestoneSchema = z.object({
  age: z.number(),
  p10: z.number(),
  p20: z.number().optional(),
  p50: z.number(),
  p80: z.number().optional(),
  p90: z.number(),
})

export const ProjectionsSchema = z.object({
  milestones: z.array(MilestoneSchema),
  successRatePct: z.number().min(0).max(100),
})

export const RecommendationSchema = z.object({
  id: z.string().optional(),
  title: z.string(),
  category: z.string(),
  body: z.string(),
  impact: z.enum(['High', 'Medium', 'Low']),
})

export const SummarySchema = z
  .object({
    planHealthScore: z.number().min(0).max(100),
    planHealthLabel: z.enum(['Strong', 'Moderate', 'Needs Attention']),
    planHealthWhy: z.string().optional(),
    planHealthWhyBits: z.array(z.string()).optional(),
    /**
     * Itemised inputs of `planHealthScore`, so the report can show how the
     * score was reached. Optional: older payloads simply omit the breakdown.
     */
    planHealthComponents: z
      .array(
        z.object({
          id: z.enum(['success', 'spending', 'liquidity']),
          value: z.number().min(0).max(100),
          weight: z.number().min(0).max(1),
        })
      )
      .optional(),
    successProbabilityPct: z.number().min(0).max(100),
    bridge: z.object({
      startAge: z.number(),
      endAge: z.number(),
      cashNeedEUR: z.number(),
      cashBucketYears: z.number().optional(),
      cashBucketSharePct: z.number().optional(),
      portfolioSharePct: z.number().optional(),
    }),
    topActions: z.array(z.string()).default([]),
    topActionsDetailed: z
      .array(
        z.object({
          title: z.string(),
          upliftMin: z.number(),
          upliftMax: z.number(),
        })
      )
      .default([]),
  })
  .optional()

export const ReportDataSchema = z.object({
  person: PersonSchema,
  finances: FinancesSchema,
  spending: SpendingSchema,
  assumptions: AssumptionsSchema,
  simulation: SimulationSchema.optional(),
  projections: ProjectionsSchema,
  summary: SummarySchema,
  recommendations: z.array(RecommendationSchema),
  metadata: z
    .object({
      reportId: z.string().default(() => `RPT-${Date.now()}`),
      generatedAt: z.string().default(() => new Date().toISOString()),
      version: z.string().default('1.0.0'),
      /**
       * Name of the plan the report was generated from. Optional so older
       * payloads (and the legacy print route) keep validating unchanged.
       */
      planName: z.string().trim().min(1).max(80).optional(),
    })
    .optional(),
  locale: ReportLocaleSchema.optional(),
})

export type Person = z.infer<typeof PersonSchema>
export type Finances = z.infer<typeof FinancesSchema>
export type Spending = z.infer<typeof SpendingSchema>
export type Assumptions = z.infer<typeof AssumptionsSchema>
export type SimulationMeta = z.infer<typeof SimulationSchema>
export type Milestone = z.infer<typeof MilestoneSchema>
export type Projections = z.infer<typeof ProjectionsSchema>
export type Recommendation = z.infer<typeof RecommendationSchema>
export type ReportData = z.infer<typeof ReportDataSchema>
export type Summary = z.infer<typeof SummarySchema>
