import { DEFAULT_PARAMS } from '@/types'

/**
 * Baked output of the app's real Monte Carlo engine.
 *
 * Generated by running `runMonteCarloSimulation()` on DEFAULT_PARAMS with
 * 5000 runs and the engine's fixed path seed, so the landing preview shows
 * genuine engine output (not an illustration) and every number on the page
 * comes from this one source of truth.
 *
 * `preview-data.test.ts` re-runs the engine and fails if these values drift
 * away from what the shipped defaults actually produce — the landing page is
 * not allowed to quote a plan the product no longer ships.
 */
export const PREVIEW_RUNS = 5000

/**
 * What a visitor's *own* first plan runs — a different number from
 * {@link PREVIEW_RUNS}, and the one the landing page has to promise, because
 * it is the one the dashboard will report back. Read from the shipped defaults
 * so the two can never drift.
 */
export const APP_DEFAULT_RUNS = DEFAULT_PARAMS.simulationRuns

/** Success rate in percent at {@link PREVIEW_RUNS}, as returned by the engine. */
export const PREVIEW_SUCCESS_RATE = 94.58

/**
 * Success rate in percent of the very same plan at the shipped default run
 * count — i.e. the number a visitor's fresh dashboard reports back. Baked from
 * the same engine so the landing page can name it instead of leaving the
 * visitor to discover the sampling gap on their own.
 */
export const PREVIEW_DEFAULT_RUNS_SUCCESS_RATE = 95.2

export const PREVIEW_PLAN = {
  currentAge: 55,
  retirementAge: 60,
  legalRetirementAge: 67,
  endAge: 90,
  currentAssets: 630000,
} as const

export const PREVIEW_AGES = [
  55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
  79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
]

export const PREVIEW_SERIES = {
  p10: [
    602714, 641564, 684982, 744487, 808378, 742353, 686926, 628087, 574849, 523732, 473839, 423370,
    426077, 412742, 403952, 405961, 403838, 397532, 391128, 396065, 389643, 381283, 384826, 372796,
    367839, 364644, 357232, 355868, 347013, 334768, 327112, 317174, 307204, 293971, 289464, 274229,
  ],
  p20: [
    640494, 696117, 758821, 829274, 903065, 852511, 813549, 769879, 731131, 685810, 648575, 589520,
    604484, 608667, 615257, 616668, 630455, 638438, 636967, 644000, 648649, 661539, 668001, 678876,
    690791, 694668, 692206, 710856, 722220, 721155, 734833, 729719, 746161, 750564, 741218, 753349,
  ],
  p50: [
    714648, 810963, 909511, 1012767, 1124996, 1113272, 1109676, 1097695, 1087443, 1071336, 1062429,
    1051594, 1089000, 1120711, 1168436, 1198323, 1234566, 1278020, 1311300, 1360265, 1401491,
    1433908, 1484395, 1513539, 1553481, 1610635, 1640447, 1678020, 1712757, 1755829, 1791755,
    1812748, 1856760, 1891972, 1916789, 1960504,
  ],
  p80: [
    796094, 944105, 1086515, 1239580, 1409677, 1463658, 1509595, 1543494, 1560251, 1602803, 1647998,
    1663366, 1778248, 1862946, 1950195, 2049610, 2159015, 2248638, 2338867, 2403651, 2516275,
    2606827, 2703921, 2786560, 2897213, 3016507, 3184090, 3252577, 3376170, 3464198, 3574585,
    3714624, 3792184, 3828796, 3980554, 4146795,
  ],
  p90: [
    841816, 1024828, 1188948, 1381971, 1579581, 1685110, 1758180, 1843553, 1913803, 1974761,
    2057668, 2150966, 2284200, 2404565, 2561713, 2666516, 2801173, 2945523, 3100393, 3210402,
    3346405, 3543381, 3715467, 3848695, 4021957, 4204070, 4374776, 4583362, 4825438, 5014733,
    5174988, 5285722, 5440214, 5717317, 5893743, 6172308,
  ],
} as const

/**
 * Years the plan covers — `endAge − currentAge`, the same arithmetic the PDF
 * prints ("35 yrs"). Not `PREVIEW_AGES.length`, which counts the *ages* on the
 * grid: 55 through 90 inclusive is 36 points but 35 years, and the stat band
 * used to claim the larger number.
 */
export const PREVIEW_HORIZON_YEARS = PREVIEW_PLAN.endAge - PREVIEW_PLAN.currentAge

/** Terminal (age 90) values, used for the hero callouts. */
export const PREVIEW_TERMINAL = {
  p10: 274229,
  p50: 1960504,
  p90: 6172308,
} as const
